// server.js
//
// Thin wrapper to run the Next.js standalone server that lives in
// .next/standalone/server.js (generated by `next build` when
// `output: "standalone"` is enabled in next.config.mjs).

const path = require("path");

// Make sure we run from the app root (same as package.json)
process.chdir(path.join(__dirname));

// This file is created by `next build` with output:"standalone"
require("./.next/standalone/server.js");
